src/Entity/ListItem.php
<?php

namespace App\Entity;

use App\Repository\ListItemRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListItemRepository::class)
 */
class ListItem
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Lists::class, inversedBy="listItems")
     * @ORM\JoinColumn(nullable=false)
     */
    private $list;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $item_name;

    /**
     * @ORM\Column(type="string")
     */
    private $placed_at;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $color;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getList(): ?Lists
    {
        return $this->list;
    }

    public function setList(?Lists $list): self
    {
        $this->list = $list;

        return $this;
    }

    public function getItemName(): ?string
    {
        return $this->item_name;
    }

    public function setItemName(string $item_name): self
    {
        $this->item_name = $item_name;

        return $this;
    }

    public function getPlacedAt(): ?string
    {
        return $this->placed_at;
    }

    public function setPlacedAt(string $placed_at): self
    {
        $this->placed_at = $placed_at;

        return $this;
    }

    public function getColor(): ?string
    {
        return $this->color;
    }

    public function setColor(?string $color): self
    {
        $this->color = $color;

        return $this;
    }
}

src/Entity/Lists.php
<?php

namespace App\Entity;

use App\Repository\ListsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ListsRepository::class)
 */

class Lists
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="lists")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity=ListItem::class, mappedBy="list", cascade={"all"}, orphanRemoval=true)
     * @ORM\OrderBy({"placed_at" = "DESC", "id" = "DESC"})
     */
    private $listItems;

    public function __construct()
    {
        $this->listItems = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection|ListItem[]
     */
    public function getListItems(): Collection
    {
        return $this->listItems;
    }

    public function addListItem(ListItem $listItem): self
    {
        if (!$this->listItems->contains($listItem)) {
            $this->listItems[] = $listItem;
            $listItem->setList($this);
        }

        return $this;
    }

    public function removeListItem(ListItem $listItem): self
    {
        if ($this->listItems->contains($listItem)) {
            $this->listItems->removeElement($listItem);
            // set the owning side to null (unless already changed)
            if ($listItem->getList() === $this) {
                $listItem->setList(null);
            }
        }

        return $this;
    }

}

src/Form/ListsType.php
<?php

namespace App\Form;

use App\Entity\Lists;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;


class ListsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            // ->add('user')
            ->add('user_id', HiddenType::class, [
                'mapped' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Lists::class,
        ]);
    }
}

src/Controller/ListsController.php
<?php

namespace App\Controller;

use App\Entity\Lists;
use App\Entity\ListItem;
use App\Form\ListsType;
use App\Form\ListItemType;
use App\Repository\ListsRepository;
use App\Repository\ListItemRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

class ListsController extends AbstractController
{
    private $listsRepository;
    private $listItemRepository;
    private $security;

    public function __construct(ListsRepository $listsRepository, Security $security, ListItemRepository $listItemRepository)
    {
        $this->listsRepository = $listsRepository;
        $this->security = $security;
        $this->listItemRepository = $listItemRepository;
    }

    /* redirect after login and fetch lists with list items*/
    public function index()
    {

        $form = $this->listForm();
        $itemform = $this->listItemForm();
        $user = $this->security->getUser();
        $user_id = $user->getId();

        if ($user->getFirstTimeLogin() == true && $user->isVerified() == false ){
            return $this->redirectToRoute("app_login");                    
        }

        /* get list and render index view */
        $lists = $this->listsRepository->findBy(['user'=>$user_id], ['id'=>'DESC']);

        return $this->render('lists/index.html.twig', [
            'lists' => $lists,
            'form' => $form->createView(),
            'itemform' => $itemform->createView()
        ]);
    }

    /* call it to make form to add list */
    public function listForm()
    {
        $list = new Lists();
        $form = $this->createForm(ListsType::class, $list);
        return $form;   
    }

    /* call it to make form to add items in list */
    public function listItemForm()
    {
        $item = new ListItem();
        $form = $this->createForm(ListItemType::class, $item);
        return $form;   
    }

    /* add new list into database */
    public function new(Request $request): JsonResponse
    {
        $data = $request->request->all();
        $form = $this->listForm();
        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            
            /* call repository function to create new list into database  */
            $add = $this->listsRepository->create($form);
            
            if ($add == "false"){
                $result['status'] = "fail";
            }else{
                $result['status'] = "success";
                $result['list']['id'] = $add->getId();
                $result['list']['encode_id'] = base64_encode($add->getId());
                $result['list']['name'] = $add->getName();
                $result['list']['url'] = $this->generateUrl("lists_delete", ['id'=>base64_encode($add->getId())] );
            }

            return new JsonResponse($result);
        }
    }

    /* get detail of list on the basis of list id*/
    public function detail($id)
    {
        $id = base64_decode($id);
        
        $result['status'] = "fail";
        $list = $this->listsRepository->find($id);
        if($list){
            $result['status'] = "success";
            $result['id'] = base64_encode($list->getId());
            $result['name'] = $list->getName();
        }

        return new JsonResponse($result);
    }

    /* edit list details through ajax */
    public function edit(Request $request)
    {
        $data = $request->request->all();
        $result['status'] = "fail";

        if ($data) {
            $update = $this->listsRepository->update($data);

            if ($update){
                $result['status'] = "success";
                $result['name'] = $update->getName();
                $result['id'] = $update->getId();
            }
        }
        return new JsonResponse($result);
    }

    /* add new item into existing list*/
    public function newListItem(Request $request): JsonResponse
    {
        $data = $request->request->all();
        $form = $this->listItemForm();
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            /* call repository function to create new item into list into database  */
            $addItem = $this->listItemRepository->create($form);

            if ($addItem == "false"){
                $result['status'] = "fail";
            }else{
                $result['status'] = "success";
                $result['item']['id'] = $addItem->getId();
                $result['item']['name'] = $addItem->getItemName();
                $result['item']['place'] = $addItem->getPlacedAt();
                $result['item']['color'] = $addItem->getColor();
                $result['item']['list'] = $addItem->getList()->getId();
                $result['item']['deleteUrl'] = $this->generateUrl("list_items_delete", ['id'=>base64_encode($addItem->getId())] );
            }
        }else{
            $result['status'] = "fail";    
        }
        
        return new JsonResponse($result);
    }

    /* to delete list and its items */
    public function delete(Request $request, $id): JsonResponse
    {
        $result['status'] = "fail";        
        $list = $this->listsRepository->find(base64_decode($id));
            
        $delete = $this->listsRepository->deleteList($list);
        if ($delete == true) {
            $result['status'] = "success";
        }

        return new JsonResponse($result);
    }

    /* to delete item from list */
    public function deleteListItem(Request $request, $id): JsonResponse
    {
        $result['status'] = 'fail';
        $listItem = $this->listItemRepository->find(base64_decode($id));
        $id = $listItem->getId();   
        $delete = $this->listItemRepository->deleteItem($listItem);
        if ($delete == true) {
            $result['status'] = "success";
        }
        return new JsonResponse($result);   
    }
}

templates/lists/index.html.twig
{% extends 'after_login.html.twig' %}

{% block title %}Lists{% endblock %}

{% block body %}
<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Lists</h1>
        <button class="btn btn-primary pull-right" data-toggle="modal" data-target="#addListModal">
            <i class="fa fa-plus"></i>
            Add new list
        </button> 
    </div>
    <div class="row listsDiv">
        {% for list in lists %}
            {% set list_id = list.id %}
            <div class="col-lg-4 listFor">
                <div class="card shadow mb-4">
                    <div class="d-block card-header py-3">
                        <a href="#collapseCardExample{{ list_id }}" class="" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample{{ list_id }}">
                            <h6 class="m-0 font-weight-bold text-primary listNameHead{{list_id}}">{{ list.name }}</h6>
                        </a>
                        <form id="deleteListForm" action="{{ path('lists_delete', {'id': list.id|base64_encode}) }}">
                            <input type="hidden" name="_method" value="DELETE">
                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ list.id) }}">
                            <button class="list_delete_icon" title="Delete list"><i class="fa fa-times "></i></button>
                        </form>

                        <a class="list_edit_icon" title="Edit list" hitUrl="{{ path('lists_detail', {'id': list_id|base64_encode}) }}"><i class="fa fa-edit"></i></a>
                    </div>
                    <div class="collapse show" id="collapseCardExample{{ list_id }}">
                        <div class="card-body">
                            <div class="item_add_btn">
                                <button class="btn btn-info add_item_btn" thisList="{{ list_id|base64_encode }}">
                                    <i class="fa fa-plus"> </i> Add item
                                </button>
                            </div>
                            
                            <div class="itemDiv thisList{{ list_id }}">
                                {% set break = true %}
                                {% for items in list.listItems %}
                                    {% if break %}
                                        {% if items.placedAt == "top" %}
                                            <div class="px-3 py-3 bg_list_item thisItem" style="color: {{items.color}};">
                                                <form id="deleteItemForm" action="{{ path('list_items_delete', {'id': items.id|base64_encode}) }}">
                                                    <input type="hidden" name="_method" value="DELETE">
                                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ items.id) }}">
                                                    <button class="itm_del_icon" title="Delete item"><i class="fa fa-times"></i></button>
                                                </form>
                                                {{ items.itemName }}
                                            </div>
                                        {% else %}
                                            {% set break = false %}
                                            {% for items in list.listItems|reverse %}
                                                {% if items.placedAt == "bottom" %}
                                                        
                                                    <div class="px-3 py-3 bg_list_item thisItem" style="color: {{items.color}};">
                                                        <form id="deleteItemForm" action="{{ path('list_items_delete', {'id': items.id|base64_encode}) }}">
                                                            <input type="hidden" name="_method" value="DELETE">
                                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ items.id) }}">
                                                            <button class="itm_del_icon" title="Delete item"><i class="fa fa-times"></i></button>
                                                        </form>
                                                        {{ items.itemName }}
                                                    </div>
                                                {% endif %}
                                            {% endfor %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        
        {% else %}

            <div class="col-lg-12 noList">
                <div class="card shadow mb-16">
                    <div class="card-body no_record">
                      No record found.
                      <a href="javascript:void(0);" data-toggle="modal" data-target="#addListModal">Create new</a>
                    </div>
                </div>
            </div>    

        {% endfor %}

    </div>
</div>

{% endblock %}